services:
  - type: web
    name: farmconnect
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: farmconnect_db
          property: connectionString
      - key: FLASK_DEBUG
        value: false

databases:
  - name: farmconnect_db
    plan: free
    databaseName: farmconnect
    user: farmconnect_user